title: the geisten project
author: Dr. Germar Schlegel
email: g.schlegel@geisten.com
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  Build your own intelligent systems that are minimally designed to run in tiny environments.
# social links
twitter_username: Germar89273479 # DO NOT include the @ character, or else the build will fail!
github_username:  geisten # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage